### ISSUE TITLE
 Failed importing jeromegillard-map  after enable map extension

### ISSUE THREAD

**Issue by asakous** [JeromeGillard/flarum-map#13]
[2023-12-20 11:08:41] flarum.ERROR: InvalidArgumentException: Failed importing jeromegillard-map due to View [jeromegillard-map] not found. in /var/www/pbs/vendor/fof/upload/src/Extenders/AddPostDownloadTags.php:52
Stack trace:
#0 /var/www/pbs/vendor/fof/upload/src/Extenders/AddPostDownloadTags.php(31): FoF\Upload\Extenders\AddPostDownloadTags->createTag()
#1 /var/www/pbs/vendor/flarum/core/src/Formatter/Formatter.php(177): FoF\Upload\Extenders\AddPostDownloadTags->FoF\Upload\Extenders\{closure}()
#2 /var/www/pbs/vendor/flarum/core/src/Formatter/Formatter.php(213): Flarum\Formatter\Formatter->getConfigurator()
#3 /var/www/pbs/vendor/illuminate/cache/Repository.php(426): Flarum\Formatter\Formatter->Flarum\Formatter\{closure}()
#4 /var/www/pbs/vendor/flarum/core/src/Formatter/Formatter.php(214): Illuminate\Cache\Repository->rememberForever()
#5 /var/www/pbs/vendor/flarum/core/src/Formatter/Formatter.php(257): Flarum\Formatter\Formatter->getComponent()
#6 /var/www/pbs/vendor/flarum/core/src/Forum/ForumServiceProvider.php(112): Flarum\Formatter\Formatter->getJs()
#7 [internal function]: Flarum\Forum\ForumServiceProvider->Flarum\Forum\{closure}()
#8 /var/www/pbs/vendor/flarum/core/src/Frontend/Compiler/Source/StringSource.php(38): call_user_func()
#9 /var/www/pbs/vendor/flarum/core/src/Frontend/Compiler/Source/StringSource.php(49): Flarum\Frontend\Compiler\Source\StringSource->getContent()
#10 /var/www/pbs/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(174): Flarum\Frontend\Compiler\Source\StringSource->getCacheDifferentiator()
#11 /var/www/pbs/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(71): Flarum\Frontend\Compiler\RevisionCompiler->calculateRevision()
#12 /var/www/pbs/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(111): Flarum\Frontend\Compiler\RevisionCompiler->commit()
#13 /var/www/pbs/vendor/flarum/core/src/Frontend/Content/Assets.php(118): Flarum\Frontend\Compiler\RevisionCompiler->getUrl()
#14 [internal function]: Flarum\Frontend\Content\Assets->Flarum\Frontend\Content\{closure}()
#15 /var/www/pbs/vendor/flarum/core/src/Frontend/Content/Assets.php(117): array_map()
#16 /var/www/pbs/vendor/flarum/core/src/Frontend/Content/Assets.php(92): Flarum\Frontend\Content\Assets->getUrls()
#17 /var/www/pbs/vendor/flarum/core/src/Frontend/Content/Assets.php(66): Flarum\Frontend\Content\Assets->addAssetsToDocument()
#18 /var/www/pbs/vendor/flarum/core/src/Frontend/Frontend.php(62): Flarum\Frontend\Content\Assets->__invoke()
#19 /var/www/pbs/vendor/flarum/core/src/Frontend/Frontend.php(54): Flarum\Frontend\Frontend->populate()
#20 /var/www/pbs/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#21 /var/www/pbs/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Frontend\Controller->handle()
#22 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#23 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#24 /var/www/pbs/vendor/fof/oauth/src/Middleware/BindRequest.php(33): Laminas\Stratigility\Next->handle()
#25 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\BindRequest->process()
#26 /var/www/pbs/vendor/fof/oauth/src/Middleware/ErrorHandler.php(58): Laminas\Stratigility\Next->handle()
#27 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\ErrorHandler->process()
#28 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#29 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#30 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#31 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#32 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#33 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#34 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#35 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#36 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#37 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process()
#38 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#39 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#40 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#41 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#42 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#43 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process()
#44 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#45 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process()
#46 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#47 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process()
#48 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#49 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CollectGarbage->process()
#50 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#51 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process()
#52 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#53 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#54 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#55 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process()
#56 /var/www/pbs/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#57 /var/www/pbs/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#58 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process()
#59 /var/www/pbs/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#60 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process()
#61 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#62 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process()
#63 /var/www/pbs/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#64 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process()
#65 /var/www/pbs/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#66 /var/www/pbs/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process()
#67 /var/www/pbs/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#68 /var/www/pbs/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#69 /var/www/pbs/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#70 /var/www/pbs/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#71 /var/www/pbs/public/index.php(26): Flarum\Http\Server->listen()
#72 {main}

**Comment by JeromeGillard** [comment]
New fix released. Could you try again with [v0.1.9](https://packagist.org/packages/jeromegillard/map#v0.1.9)?

**Comment by asakous** [comment]
the  errors is gone. thanks
